trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndTest
  displayName: "Compilar y ejecutar pruebas"
  jobs:
  - job: Build
    steps:
    - checkout: self
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'clean test aggregate'
        publishJUnitResults: true
        testResultsFiles: '**/build/test-results/test/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'build/reports'
        artifactName: 'serenity-report'
        publishLocation: 'Container'

- stage: Deploy
  displayName: "Desplegar en ambiente QA"
  dependsOn: BuildAndTest
  condition: succeeded()   # Solo si las pruebas pasan
  jobs:
  - job: DeployJob
    steps:
    - download: current
      artifact: serenity-report

    - script: echo "Aquí irían tus pasos de despliegue 🚀"
      displayName: "Desplegando aplicación en QA"